SELECT nombre FROM producto;
SELECT nombre, precio FROM producto;
SELECT * FROM producto;
SELECT nombre, precio, precio * 1.08 AS dolar_price FROM producto;
SELECT nombre AS nom_de_producto, precio AS euros, ROUND(precio * 1.08, 2) AS dolar_price FROM producto;
SELECT UPPER(nombre) AS nombre, UPPER(precio) AS precio FROM producto;
SELECT LOWER(nombre) AS nombre, LOWER(precio) AS precio FROM producto;
SELECT nombre, UPPER(SUBSTRING(nombre, 1, 2)) AS Abbreviation FROM fabricante;
SELECT nombre, ROUND(precio) FROM producto; 
SELECT nombre, TRUNCATE(precio, 0) FROM producto;
SELECT codigo_fabricante FROM producto;
SELECT codigo_fabricante FROM producto GROUP BY codigo_fabricante;
SELECT nombre FROM fabricante ORDER BY nombre ASC;
SELECT nombre FROM fabricante ORDER BY nombre DESC;
SELECT nombre FROM producto ORDER BY nombre ASC, precio DESC;
SELECT * FROM fabricante LIMIT 5;
SELECT * FROM fabricante LIMIT 2 OFFSET 3;
SELECT nombre, precio FROM producto ORDER BY precio ASC LIMIT 1;
SELECT nombre, precio FROM producto ORDER BY precio DESC LIMIT 1;
SELECT nombre FROM producto WHERE codigo_fabricante = 2;
SELECT p.nombre, p.precio, f.nombre AS nombre_fabricante FROM producto p JOIN fabricante f ON p.codigo_fabricante = f.codigo;
SELECT p.nombre, p.precio, f.nombre AS nombre_fabricante FROM producto p JOIN fabricante f ON p.codigo_fabricante = f.codigo ORDER BY f.nombre;
SELECT p.codigo AS codigo_producto, p.nombre, f.codigo AS codigo_fabricante, f.nombre AS nombre_fabricante FROM producto p JOIN fabricante f ON p.codigo_fabricante = f.codigo;
SELECT p.nombre, p.precio, f.nombre AS nombre_fabricante FROM producto p JOIN fabricante f ON p.codigo_fabricante = f.codigo ORDER BY p.precio LIMIT 1;
SELECT p.nombre, p.precio, f.nombre AS nombre_fabricante FROM producto p JOIN fabricante f ON p.codigo_fabricante = f.codigo ORDER BY p.precio DESC LIMIT 1;
SELECT p.nombre, p.precio, f.nombre AS nombre_fabricante FROM producto p JOIN fabricante f ON p.codigo_fabricante = f.codigo WHERE f.nombre IN ('Lenovo');
SELECT p.nombre, p.precio, f.nombre AS nombre_fabricante FROM producto p JOIN fabricante f ON p.codigo_fabricante = f.codigo WHERE f.nombre = 'Crucial' AND p.precio > 200;
SELECT p.nombre, p.precio, f.nombre AS nombre_fabricante FROM producto p JOIN fabricante f ON p.codigo_fabricante = f.codigo WHERE f.nombre = 'Hewlett-Packard' OR f.nombre = 'Asus' OR f.nombre ='Seagate';
SELECT p.nombre, p.precio, f.nombre AS nombre_fabricante FROM producto p JOIN fabricante f ON p.codigo_fabricante = f.codigo WHERE f.nombre IN ('Hewlett-Packard', 'Asus', 'Seagate');
SELECT p.nombre, p.precio FROM producto p JOIN fabricante f ON p.codigo_fabricante = f.codigo WHERE f.nombre REGEXP ('e$');
SELECT p.nombre, p.precio FROM producto p JOIN fabricante f ON p.codigo_fabricante = f.codigo WHERE f.nombre LIKE ('%w%');
SELECT p.nombre, p.precio, f.nombre AS nombre_fabricante FROM producto p JOIN fabricante f ON p.codigo_fabricante = f.codigo WHERE p.precio >= 180 ORDER BY p.precio DESC, p.nombre;
SELECT f.codigo, f.nombre AS nombre_fabricante FROM producto p JOIN fabricante f ON p.codigo_fabricante = f.codigo GROUP BY f.codigo;
SELECT f.nombre AS nombre_fabricante, p.nombre AS nombre_producto FROM producto p RIGHT	JOIN fabricante f ON f.codigo = p.codigo_fabricante;
SELECT f.nombre AS nombre_fabricante, p.nombre AS nombre_producto FROM producto p RIGHT	JOIN fabricante f ON f.codigo = p.codigo_fabricante WHERE p.nombre IS null;
SELECT f.nombre AS nombre_fabricante, p.nombre AS nombre_producto FROM producto p LEFT JOIN fabricante f ON (p.codigo_fabricante = f.codigo) WHERE f.nombre IN ('lenovo');
SELECT * FROM producto WHERE precio IN (SELECT MAX(precio) FROM producto p LEFT JOIN fabricante f ON (p.codigo_fabricante = f.codigo) WHERE f.nombre IN ('lenovo'));
SELECT f.nombre AS nombre_fabricante, p.nombre AS nombre_producto, p.precio FROM producto p LEFT JOIN fabricante f ON (p.codigo_fabricante = f.codigo) WHERE f.nombre IN ('lenovo') ORDER BY p.precio DESC LIMIT 1;
SELECT f.nombre AS nombre_fabricante, p.nombre AS nombre_producto, p.precio FROM producto p LEFT JOIN fabricante f ON (p.codigo_fabricante = f.codigo) WHERE f.nombre IN ('Hewlett-Packard') ORDER BY p.precio ASC LIMIT 1;
SELECT * FROM producto WHERE precio >= (SELECT MAX(precio) FROM producto p LEFT JOIN fabricante f ON (p.codigo_fabricante = f.codigo) WHERE f.nombre IN ('lenovo'));
SELECT * FROM producto p JOIN fabricante f ON f.codigo = p.codigo_fabricante WHERE f.nombre IN ('Asus') AND precio > (SELECT AVG(precio) FROM producto p LEFT JOIN fabricante f ON (p.codigo_fabricante = f.codigo) WHERE f.nombre IN ('asus'));


